### PR TITLE
Sample commit to see how GIT works

### PR DESCRIPTION
**Pull request by Gilberto97**

### CODE REVIEW

**Comment by ljharb** [comment]
Please make these sort of commits on your own repositories; it's not polite to pollute other people's code just to experiment.

**Comment by Gilberto97** [comment]
Hi, sorry for that :) Im beginner So thanks for Your advice, and once more
time - sorry!
Greetigs from Poland

**Comment by ljharb** [comment]
@Gilberto97 no problem :-) just something to know for next time.

**Comment by ntwb** [comment]
I think you'll find these types of commits are people trying to get a free t-shirt from hacktoberfest

**Comment by ljharb** [comment]
@ntwb i'm aware, that's why i marked it as "invalid", so it doesn't count for the shirt.

**Pull request closed without merging**
